### PR TITLE
common: add sensor driver u50su4p180pmdafc bmr313 mp2891 raa228238 mpc12109

### PR DESCRIPTION
**Pull request by Victor-Jhong**
Summary:

- Add u50su4p180pmdafc UBC sensor driver
- Add bmr313 UBC sensor driver
- Add mpc12109 UBC sensor driver
- Add mp2891 VR sensor driver
- Add raa228238 VR sensor driver

Test plan:

- Build code: PASS
- Get sensor reading: PASS

### CODE REVIEW

**Comment by Prabha-Veerubhotla** [comment]
@Victor-Jhong can you please fix the `run-cppcheck` failure

**Review by Prabha-Veerubhotla — CHANGES_REQUESTED** [review]
please fix the `run-cppcheck` error

**Comment by Victor-Jhong** [comment]
The cppcheck error results from the weak definition of pal_get_monitor_sensor_count(), which returns 0 by default. This is expected behavior, as it's designed to be overridden by other platform-defined functions. On platforms where it is overridden, the logic will work correctly.

**Comment by Victor-Jhong** [comment]
Hi @Prabha-Veerubhotla , I've rebased to the newest main, please help review. Thanks!

**Pull request closed without merging**
