### PR TITLE
fby35: ji: Initialize Java Island BIC

### PR DESCRIPTION
**Pull request by MouchenHung-QUANTA**
Summary:
- Initialize Java Island BIC.
- Create project config, dts files, file header, and CMake file.
- Add project code in meta-facebook/yv35-ji/.

Test Plan:
- Build code: pass

Test Log:
```
$ west build -p auto -b ast1030_evb meta-facebook/yv35-ji/
[265/271] Linking C executable zephyr/zephyr_prebuilt.elf

[271/271] Linking C executable zephyr/Y35BJI.elf
Memory region         Used Size  Region Size  %age Used
         SRAM_NC:          0 GB        60 KB      0.00%
           FLASH:          0 GB         0 GB
            SRAM:      433192 B       708 KB     59.75%
        IDT_LIST:          0 GB         2 KB      0.00%
```

### CODE REVIEW

**Comment by jagpalgill** [comment]
@MouchenHung-QUANTA Can you please perform a rebase on this diff?

**Review by jagpalgill — CHANGES_REQUESTED** [review]
@MouchenHung-QUANTA Can you please perform a rebase on this diff?

**Review by jagpalgill — CHANGES_REQUESTED** [review]
Noticing clang format errors. Please fix them -

https://github.com/facebook/OpenBIC/actions/runs/8092736301/job/22114006616

https://github.com/facebook/OpenBIC/actions/runs/8092736301/job/22114008077

**Review by jagpalgill — CHANGES_REQUESTED** [review]
@MouchenHung-QUANTA I am still noticing a github build failure for y3.5

https://github.com/facebook/OpenBIC/actions/runs/8105796944/job/22154692646

**Comment by MouchenHung-QUANTA** [comment]
Hi Jagpal,

It appears that the build failure for yv35-bb is not caused by this code. Please Check it. Thanks.

Thanks!

**Pull request closed without merging**
