### PR TITLE
Optimize Crater Lake IPMI (main_v2)

### PR DESCRIPTION
**Pull request by DelphineChiu**
Note: This is the first package in PR189 (subset of PR189)
-------------------------------------------
Optimize CL IPMI and libraries
Summary:
    - Move IPMI handler from project code to common code.
    - Move some IPMI handler related libraries from project code to common code.
    - Reconstruct folders: create "hal", "lib" directory in common code.
         -lib: Includes common library for corresponding feature or general sharing between different threads.
               Such as FRU, GUID, Firmware update, …, and Utility Library (eg. checksum function, etc).
         -hal: This is hardware abstract layer which includes I2C, PECI, GPIO and JTAG communication API.

### CODE REVIEW

**Comment by GoldenBug** [comment]
Should this be building on Yv3.5 BB or is it expected not to in this state?

**Comment by DelphineChiu** [comment]
Hi @GoldenBug 
image

The pic shows OpenBIC code optimization sequence.  
For each PR, BB should also be building but we didn't modify the BB portion at the beginning. 

Do you observe any issues on building BB BIC?

**Reminder**: 
Pls review code **from this PR** and **not**from PR #189 because PR #189 is only for architecture overview and is out-of-date.

**Comment by DelphineChiu** [comment]
Hi @GoldenBug 
Just saw the CI build BB fail - would you mind to let it go first. let's see the BB build status at the PR for BB change.

**Comment by GoldenBug** [comment]
Yes I think that's fine in order to keep this moving.

**Comment by GoldenBug** [comment]
Committed seperately

**Pull request closed without merging**
