### PR TITLE
fby3.5: cl: Host bridge message failure handle

### PR DESCRIPTION
**Pull request by Yi-Shum**
Summary:
- Add an else if statement to the IPMB_TXTask to print error message when the bridge message from the host reaches the maximum number of retries.

Test Plan:
- Build code: Pass

### CODE REVIEW

**Comment by GoldenBug** [comment]
Hi, Could you rebase this on the current main branch.
There were some problems with the tests that should be fixed now. 

Thanks!

**Comment by Yi-Shum** [comment]
Hi @GoldenBug,
We've forced updated the PR to rebase the main branch.
Please help to review again, thank you.

**Comment by Yi-Shum** [comment]
Hi @GoldenBug,
We've merged the PR to the main branch.
Please help to review again, thank you.

**Comment by Yi-Shum** [comment]
Add KCS fail handle at #169

**Pull request closed without merging**
