### PR TITLE
minerva-ag: Support log recording and cpld polling and emc1413

### PR DESCRIPTION
**Pull request by Victor-Jhong**
Summary:

- Support log recording and cpld polling
- Support pldm shell command
- Add sensor threshold at PDR
- Support sensor emc1413
- Support keyword search at shell command list_all_sensor
- Support clk gen and eusb settings

Test Plan:

- Build code: PASS
- LOG generate: PASS
- LOG dump: PASS
- pldm shell command test: PASS
- Threshold display at BMC: PASS
- EMC1413 sensor read: PASS
- Shell command keyword search: PASS
- clk gen and eusb settings: PASS

### CODE REVIEW

**Comment by williamspatrick** [comment]
This commit series is rather large and has cppcheck failures.  Can we break it out into a few PRs and clean up the lint issues?

**Comment by Victor-Jhong** [comment]
Would it be possible to add unknownMacro to the cppcheck-suppressions.txt file? The code should be fine, as any issues with this macro would cause the build to fail.

**Comment by Victor-Jhong** [comment]
Since we are developing CLI commands based on project requirements, the primary features in this PR are all related to shell commands and involve changes to the same file. Due to their dependencies, splitting them into separate PRs would require waiting for the first PR to be merged before submitting the next one. For this reason, we’ve included them in the same PR as separate commits.

We’ll try to avoid this in the future, and we appreciate your consideration and understanding on this matter!

**Comment by Victor-Jhong** [comment]
I’ve rebased to the latest. Thank you!

**Comment by Victor-Jhong** [comment]
We have resolved the failing cpp check issues. Regarding the issue "common/shell/commands/sensor_shell.c:305:84:Parameter 'argv' can be declared with const", the function followed the Zephyr original prototype to declare. This exception has been reviewed and approved for ignoring by Amithash.

**Pull request closed without merging**
